package end.liuwen.com.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import end.liuwen.com.greendao.Entity.student;
import end.liuwen.com.greendao.Entity.UserInfo;

import end.liuwen.com.greendao.dao.studentDao;
import end.liuwen.com.greendao.dao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final studentDao studentDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(studentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        studentDao = new studentDao(studentDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(student.class, studentDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        studentDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public studentDao getStudentDao() {
        return studentDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
