package star.liuwen.com.endgreendao3.Dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import star.liuwen.com.endgreendao3.Bean.User;
import star.liuwen.com.endgreendao3.Bean.Test;

import star.liuwen.com.endgreendao3.Dao.UserDao;
import star.liuwen.com.endgreendao3.Dao.TestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig testDaoConfig;

    private final UserDao userDao;
    private final TestDao testDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        testDaoConfig = daoConfigMap.get(TestDao.class).clone();
        testDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        testDao = new TestDao(testDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Test.class, testDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        testDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public TestDao getTestDao() {
        return testDao;
    }

}
